const colormap={
            "Soft Pink":"#FFC0CB",
            "Mint Green":"#3EB489",
            "Powder Blue":"#B6D0E2",
            "Light Yellow":"#FFFFED",
            "Light grays":"#d3d3d3",
            "Creams":"#FFFDD0",
            "Beiges":"#F5F5DC",
            "Coral":"#FF7F50",
            "Lavender":"#E6E6FA",
            "Sky blue":"#87CEEB",
            "Light emerald green":"#50C878",
            "Soft ruby red":"#E0115F",
            "Light sapphire blue":"#395e98",
            "Terracotta":"#E2725B",
            "Olive Green":"#BAB86C",
            "Warm Brown":"#964B00",
            "Teal":"#008080",
            "Burgundy":"#800020",
            "Mustard yellow":"#FFDB58",
            "Camel":"#C19A6B",
            "Khaki":"#F0E68C",
            "Warm beige":"#D3B69C",
            "Royal purple":"#7851a9",
            "Deep emerald green":"#046307",
            "Ruby red":"#9b111e",
            "Cobalt Blue":"#0047AB", 
            "Fuchsia Pink":"#FF00FF", 
            "Deep Burgundy":"#650015", 
            "Bronze":"#CD7F32",
            "Bright orange":"#FFA500",
            "Olive":"#808000",
            "Chocolate brown":"#3f000f",
            "Gold":"#FFD700",
            "Copper":"#b87333",
            "Eggplant purple":"	#483248",
            "Forest green":"#228B22",
            "Sapphire blue":"#0F52BA"
        }
export default colormap;