let data=[
    {
        id:1,
        color:"black",
        image:"../src/images/Daily/black1.jpg"
    },
    {
        id:2,
        color:"black",
        image:"../src/images/Daily/black2.jpg"
    },
    {
        id:3,
        color:"black",
        image:"../src/images/Daily/black3.jpg"
    },
    {
        id:4,
        color:"black",
        image:"../src/images/Daily/black4.jpg"
    },
    {
        id:5,
        color:"blue",
        image:"../src/images/Daily/blue1.jpg"
    },
    {
        id:6,
        color:"black",
        image:"../src/images/Daily/blue2.jpg"
    },
    {
        id:7,
        color:"blue",
        image:"../src/images/Daily/blue3.jpg"
    },
    {
        id:8,
        color:"brown",
        image:"../src/images/Daily/brown1.jpg"
    },
    {
        id:9,
        color:"colorful",
        image:"../src/images/Daily/color.jpg"
    },
    {
        id:10,
        color:"colorful",
        image:"../src/images/Daily/color1.jpg"
    },
    {
        id:11,
        color:"colorful",
        image:"../src/images/Daily/color2.jpg"
    },
    {
        id:12,
        color:"green",
        image:"../src/images/Daily/green1.jpg"
    },
    {
        id:13,
        color:"green",
        image:"../src/images/Daily/green2.jpg"
    },
    {
        id:31,
        color:"green",
        image:"../src/images/Daily/green3.jpg"
    },
    {
        id:14,
        color:"orange",
        image:"../src/images/Daily/org1.jpg"
    },
    {
        id:15,
        color:"peach",
        image:"../src/images/Daily/peach1.jpg"
    },
    {
        id:16,
        color:"peach",
        image:"../src/images/Daily/peach2.jpg"
    },
    {
        id:17,
        color:"pink",
        image:"../src/images/Daily/pink1.jpg"
    },
    {
        id:18,
        color:"pink",
        image:"../src/images/Daily/pink2.jpg"
    },
    {
        id:19,
        color:"pink",
        image:"../src/images/Daily/pink3.jpg"
    },
    {
        id:20,
        color:"pink",
        image:"../src/images/Daily/pink4.jpg"
    },
    {
        id:21,
        color:"purple",
        image:"../src/images/Daily/purple1.jpg"
    },
    {
        id:22,
        color:"purple",
        image:"../src/images/Daily/purple2.jpg"
    },
    {
        id:23,
        color:"red",
        image:"../src/images/Daily/red1.jpg"
    },
    {
        id:24,
        color:"red",
        image:"../src/images/Daily/red2.jpg"
    },
    {
        id:25,
        color:"white",
        image:"../src/images/Daily/white1.jpg"
    },
    {
        id:26,
        color:"white",
        image:"../src/images/Daily/white2.jpg"
    }, {
        id:27,
        color:"white",
        image:"../src/images/Daily/white3.jpg"
    },
    {
        id:28,
        color:"yellow",
        image:"../src/images/Daily/yellow1.jpg"
    },
    {
        id:29,
        color:"yellow",
        image:"../src/images/Daily/yellow2.jpg"
    },
    {
        id:30,
        color:"yellow",
        image:"../src/images/Daily/yellow3.jpg"
    },
]

export default data;